select * from customers limit 10;

-- Q1.what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount)as revenue
from customers
group by gender;
-- Q2.which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customers
where discount_applied ='Yes'
and purchase_amount > (
select AVG(purchase_amount)
from customers
);

-- Q3.which are the top 5 products with the highest average review rating?
select item_purchased,
ROUND(AVG(review_rating),2) as "Average Product Rating"
from customers
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Q4.compare the average puurchase amounts between stanadard and express shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5.Do subscribed customers spemd more? compare average spend and total revenue between subscribers
-- and non subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q6.which five products have the highest percentage with discount applied?
select item_purchased,
ROUND(
SUM(CASE WHEN discount_applied = 'Yes'THEN 1 ELSE 0 END)
*100.0/count(*),
2
) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7.segments customers into new ,returning, and loyal based on their total number of 
-- previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE'Loyal'
    END as customer_segment
from customers
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8.what are the top 3 most purchased products within each category?
WITH item_counts AS(
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customers
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        category,
        item_purchased,
        total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)
SELECT
    category,
    item_purchased,
    total_orders
FROM ranked_items
WHERE item_rank <= 3;

-- Q9.are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases >5
group by subscription_status;

-- Q10.what is the revenue contribution of each group are?
select age_group,
sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue DESC;




